/**
 * This code was generated by Builder.io.
 */
import { Component } from "@angular/core";

@Component({
  selector: "app-root",
  template: "<app-money-transfer></app-money-transfer>",
  styles: [],
})
export class AppComponent {
  title = "money-transfer-app";
}
