/**
 * This code was generated by Builder.io.
 */
import { NgModule } from "@angular/core";
import { BrowserModule } from "@angular/platform-browser";
import { AppComponent } from "./app.component";
import { MoneyTransferModule } from "./money-transfer/money-transfer.module";

@NgModule({
  declarations: [AppComponent],
  imports: [BrowserModule, MoneyTransferModule],
  providers: [],
  bootstrap: [AppComponent],
})
export class AppModule {}
