/**
 * This code was generated by Builder.io.
 */
import { Component, Input } from "@angular/core";

@Component({
  selector: "app-confirmation",
  templateUrl: "./confirmation.component.html",
  styleUrls: ["./confirmation.component.css"],
})
export class ConfirmationComponent {
  @Input() mtcn: string;
  @Input() senderEmail: string;
}
