/**
 * This code was generated by Builder.io.
 */
import { Component, Input } from "@angular/core";

@Component({
  selector: "app-header",
  templateUrl: "./header.component.html",
  styleUrls: ["./header.component.css"],
})
export class HeaderComponent {
  @Input() userName: string;
  @Input() lastLogin: string;
}
