/**
 * This code was generated by Builder.io.
 */
import { Component } from "@angular/core";

@Component({
  selector: "app-money-transfer",
  templateUrl: "./money-transfer.component.html",
  styleUrls: ["./money-transfer.component.css"],
})
export class MoneyTransferComponent {
  userName: string = "User-1";
  lastLogin: string = "02, Nov, 2022 | 14:02";
  mtcn: string = "734 - 466 - 8109";
  senderEmail: string = "sender_name@demo.com";
}
