/**
 * This code was generated by Builder.io.
 */
import { NgModule } from "@angular/core";
import { CommonModule } from "@angular/common";
import { MoneyTransferComponent } from "./money-transfer.component";
import { SidebarComponent } from "./sidebar/sidebar.component";
import { HeaderComponent } from "./header/header.component";
import { ProgressBarComponent } from "./progress-bar/progress-bar.component";
import { ConfirmationComponent } from "./confirmation/confirmation.component";
import { ReceiptComponent } from "./receipt/receipt.component";

@NgModule({
  declarations: [
    MoneyTransferComponent,
    SidebarComponent,
    HeaderComponent,
    ProgressBarComponent,
    ConfirmationComponent,
    ReceiptComponent,
  ],
  imports: [CommonModule],
  exports: [MoneyTransferComponent],
})
export class MoneyTransferModule {}
